config/routes.rb
Rails.application.routes.draw do

  resources :books
  root "static_page#home"

  get "/help", to: "static_page#help"
  get "/about", to: "static_page#about"
  get "/contact", to: "static_page#contact"
  get "/contact", to: "static_page#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/admin", to: "admins#index"
  get "/createre", to: "restaurants#new"
  get "/showres", to: "restaurants#show"
  get "/searchre", to: "restaurants#search"
  get "/createfo", to: "foods#new"

  resources :users
  resources :ratings
  resources :foods
  resources :restaurants
  resources :account_activations, only: [:edit]
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :foods, dependent: :destroy
  has_many :ratings, foreign_key: "restaurant_id", dependent: :destroy
  # has_many :user_ratings, through: :users, source: ratings

  validates :name, presence: true
  validates :location, presence: true

  mount_uploader :image, RestaurantPictureUploader
  validate :image_size

  def rating user_id
    users_rating << user_id
  end

  def rated? user
    users.include?(user)
  end

  def self.search(search)
    if search
      where('LOWER(name) LIKE :search', search: "%#{search.downcase}%")
    else
      Restaurant.first(5)
    end
  end

  def calculate_new_point (current_point, new_rated_point, current_number_of_ratings)
    return (current_point + new_rated_point) / (current_number_of_ratings + 1)
  end

  def update_point params
    current_restaurant = Restaurant.find_by(id: params[:restaurant_id])
    current_quality_point = current_restaurant.quality_point
    current_service_point = current_restaurant.service_point
    current_space_point = current_restaurant.space_point
    current_price_point = current_restaurant.space_point
    current_location_point = current_restaurant.location_point
    current_number_of_ratings = current_restaurant.number_of_rated

    new_number_of_ratings = current_number_of_ratings + 1
    new_quality_point = calculate_new_point(current_quality_point, params[:quality_point].to_f, current_number_of_ratings)
    new_service_point = calculate_new_point(current_service_point, params[:service_point].to_f, current_number_of_ratings)
    new_space_point = calculate_new_point(current_space_point, params[:space_point].to_f, current_number_of_ratings)
    new_price_point = calculate_new_point(current_price_point, params[:price_point].to_f, current_number_of_ratings)
    new_price_point = calculate_new_point(current_location_point, params[:location_point].to_f, current_number_of_ratings)


    update_attribute(:number_of_rated, new_number_of_ratings)
    update_attribute(:quality_point, new_quality_point)
    update_attribute(:service_point, new_service_point)
    update_attribute(:space_point, new_space_point)
    update_attribute(:price_point, new_price_point)
    update_attribute(:location_point, new_price_point)

    # update_attribute(:reset_sent_at, Time.zone.now)
  end

  def image_size
    if image.size > Settings.maxmimum_image_size.megabytes
      errors.add(:image, t("image_size_info"))
    end
  end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]

  def index

  end

  def search
    @restaurants = Restaurant.search(params[:search])
  end

  def show
    remember_res params[:id]
    @foods = @restaurant.foods
    @rating = Rating.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new restaurant_params
    if @restaurant.save
      flash[:success] = t("create_restaurant_success")
      redirect_to admin_url
    else
      flash[:info] = t("failure")
      render :new
    end
  end

end
private
  def restaurant_params
    params.require(:restaurant).permit(:name, :location, :minprice, :maxprice, :image)
  end

  def find_restaurant
    @restaurant = Restaurant.find_by(id: params[:id])

    if @restaurant.nil?
      render "layouts/notfound"
    end
  end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def remember_res restaurantid
    cookies.permanent.signed[:restaurant_id] = restaurantid
  end

  def current_restaurant
   @current_restaurant ||= Restaurant.find_by(id: cookies.signed[:restaurant_id])
 end

  def exist_restaurant
    unless current_restaurant
      render "layouts/notfound"
    end
  end

  def rated? restaurant
    if restaurant.number_of_rated > 0
      return true
    else
      return false
    end
  end

  def calculate_avg_point restaurant
    return (restaurant.quality_point + restaurant.price_point + restaurant.space_point + restaurant.service_point + restaurant.location_point) / 5
  end

  def left_idx i
    return i * 2
  end

  def right_idx i
    return i * 2 + 1
  end
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <%= render "shared/error_messages", object: @restaurant %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :location %>
  <%= f.text_field :location, class: "form-control" %>

  <%= f.label :minprice %>
  <%= f.number_field :minprice, class: "form-control" %>

  <%= f.label :maxprice %>
  <%= f.number_field :maxprice, class: "form-control" %>
  <br>

  <span class="picture">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
  <br>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $("#restaurant_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > Settings.maxmimum_image_size) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
    }
  });
</script>


<!-- t.string :name
      t.string :location
      t.integer :total_ratings
      t.float :ratings
      t.integer :minprice
      t.integer :maxprice
      t.string :open_time
      t.string :close_time
      t.integer :total_reviews
 -->

app/views/restaurants/_restaurant.html.erb
<div class="col-md-3">
  <div class="thumbnail">

    <% if restaurant.image? %>
      <%= image_tag restaurant.image.url %>
    <% else %>
      <%= image_tag("coming_soon.jpg", height: "180", width: "240") %>
    <% end %>
    <div class="caption">
      <p><strong><%= link_to restaurant.name, restaurant %></strong></p>
      <p><%= restaurant.location %></p>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<% provide(:title, t("create_restaurant")) %>
<% provide(:button_text, t("create_restaurant")) %>
<h1><%= t("create_restaurant") %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= render "form" %>
  </div>
</div>

app/views/restaurants/search.html.erb
<h4><%= t("search_restaurant") %></h4>
<%= form_tag(searchre_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search], placeholder: "Restaurant name") %>
  <br>
  <br>
  <%= submit_tag t("search") %>
<% end %>
<% @restaurants.each do |restaurant| %>
  <ul>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li><br>
  </ul>
<% end %>